### ISSUE TITLE
Original Source

### ISSUE THREAD

**Issue by cmahte** [fallingduck/thomson-septuagint#1]
If I'm reading your about correctly, you are using a 1904 reprint to produce this text. 

I show the original text is available at 

https://books.google.com/books?id=7JgXAAAAYAAJ&pg=PP7&output=html

I'm wondering why you chose the reprint to start from?  and 2, If there are multiple OCR's, producing a error free version becomes much more likely if you use both and run a merge process on them.

**Comment by cmahte** [comment]
my bad.. incomplete records... but that's vol 3 of 4.

**Comment by cmahte** [comment]
But there are all 4 volumes from original printing, and 2 volumes from 1904 reprint (If I'm seeing it correctly) at the internet archive: https://archive.org/search.php?query=Charles%20Thomson%20Bible

**Comment by jackvandrunen** [comment]
The main textual sources I've found online for the Thomson Bible are (besides the Internet Archive) http://thetencommandmentsministry.us/ministry/charles_thomson/ and http://studybible.info/version/Thomson

I wrote a script which extracted the text at studybible.info and converted it into USFM (not included in the repo). From there, I manually go through and edit it according to the 1904 reprint. My goal for this is to have a highly accurate, [copyfree](http://copyfree.org/) reproduction of this valuable work in usable form for hackers and scholars alike. Unfortunately, it's fallen a bit by the wayside.

**Comment by cmahte** [comment]
I'd like to see that script, understanding it's not programming but problem
solving. I do understand if you don't want to release it. My process is to
Manually get to verse per line, then apply tags, manually, then break the
text into books.

I've done this many times, mostly hobby but professionally too. The point I
was trying to make is: comparative editing is nearly automatic with the
right tools (**) That is, if you can get different sources, it is MUCH
faster to do the initial tagging twice then look at differences in the
result, than it is to do it once and visually copyedit the singular result.

That is, if you can run the same script on 2 different texts OCR'd from
different printings, then 'diff' the two, you have a nearly perfect list of
all the OCR problems, or in some cases actual differences between the
printings. With the right program, you can merge the correct word over each
OCR error with a click. (I use text wrangler on a Mac, haven't found
anything like it in linux. I don't run windows.)  The more different the
process is, the less likely the same error is present in both texts.

The resulting text still probably has errors, but it should now be in the 1
every 10 chapters range, instead of multiple every verse.

----

(**) - (says the guy who's spent about 40 hours on a KJV variant published
by Oxford and is only 50% done: KJV has so many 'sources' available, the
little things that come out of hiding this way take a lot more research.
That, and 'added words' italics in the only printing of this work don't OCR
very well, and the OCR system is amazingly creative and didn't follow a set
failure mode.)

**Comment by jackvandrunen** [comment]
Sorry for the late reply! I threw the scraper script (hacky as it is) into a gist here: https://gist.github.com/fallingduck/eceb8209188981cb58fdb518fa0cfafc
